dist: xenial
sudo: required

branches:
  only:
    - master

cache:
    directories:
      - $HOME/.cache
 
env:
    global:
      - PRODUCT=netease-cloud-music

matrix:
    include:
        - os: linux
          env: OS=ubuntu EXTEN=appimage
          services: docker
          language: cpp
        # - os: linux
        #   env: OS=fedora EXTEN=appimage
        #   services: docker
        #   language: cpp
       
before_install:

install:


script:
  - export ROOT_PATH="$(pwd)"
  - bash pkg2appimage-with-docker netease-cloud-music.yml

after_success:
  - cd ${ROOT_PATH}/out
  - if [[ "${EXTEN}" == "appimage" ]]; then python3 ${ROOT_PATH}/scripts/services/transferwee.py upload NetEase_Cloud_Music-1.2.0.2.*.AppImage fi