dist: xenial
sudo: required

branches:
  only:
    - master

cache:
    directories:
      - $HOME/.cache
 
env:
    global:
      - PRODUCT=netease-cloud-music

matrix:
    include:
        - os: linux
          env: OS=ubuntu EXTEN=appimage
          services: docker
          language: cpp
        # - os: linux
        #   env: OS=fedora EXTEN=appimage
        #   services: docker
        #   language: cpp
       
before_install:

install:


script:
  - export ROOT_PATH="$(pwd)"
  - chmod +x ${ROOT_PATH}/scripts/*.sh
  - chmod +x ${ROOT_PATH}/scripts/services/*.sh
  - bash pkg2appimage-with-docker netease-cloud-music.yml

after_success:
  - cp ${ROOT_PATH}/out/*.AppImage ${ROOT_PATH}/scripts/services
  - if [[ "${EXTEN}" == "appimage" ]]; then source ${ROOT_PATH}/scripts/appimage_after_success.sh; fi
  - echo $TEMP_DOWNLOAD_URL 